### PR TITLE
refactor vm to use Unix.establish_server

### PR DESCRIPTION
**Pull request by dwightguth**
Fixes [CGKIELE-157]

### CODE REVIEW

**Comment by dwightguth** [comment]
It accomplishes two things. First, by using establish_server, we get true parallelism in the server because it forks processes rather than relying on threads, which are not truly concurrent in ocaml.

And second, if one of the connections crashes, it does not crash the server itself (because it's a separate process)

**Comment by bmmoore** [comment]
Ah, I forgot that threads are not parallel. How were connections crashing? If it was raising an exception it should be possible to handle without losing the whole server, if it's crashing worse than that then it should be investigated further.

**Comment by dwightguth** [comment]
IOHK reported an End_of_file exception. I'm not entirely sure why it wasn't getting handled internally to the connection, but it wasn't. I have tested the code with some bad packets though and intend to add those tests to the iele semantics once this is merged.

**Comment by dwightguth** [comment]
After discussion with IOHK it turns out that the bug that I was trying to fix is unrelated to this change. That said, this is still a good refactoring and so I'm going to merge it.

**Pull request merged**
