### PR TITLE
Update blockchain plugin to make IELE build

### PR DESCRIPTION
**Pull request by dwightguth**

### CODE REVIEW

**Review by gtrepta — COMMENTED** [review]
Do the contents of the `vm/` folder need to be in this repo? I'm wondering if it would be better to have them in the iele repo so there would be less friction in case they need to be changed. Keeping as much out of the blockchain-k-plugin and in its respective repo seems like a good idea overall to me.

**Review by anvacaru — APPROVED** [review]

**Comment by ehildenb** [comment]
I agree with @gtrepta that moving as much IELE specific stuff to the IELE repo makes sense. Easier to maintain there too.

**Comment by ehildenb** [comment]
@dwightguth ping

**Comment by ehildenb** [comment]
I'm also happy to merge this as-is, and have a follow up task for migrating it to IELE repo.

**Comment by dwightguth** [comment]
Let's do cleanup in a later step. There is lots of cleanup that can be done, but I would rather get things working like they used to as quickly as possible so that we have a complete set of tests for future alterations and refactoring.

**Review by ehildenb — APPROVED** [review]

**Pull request merged**
