### PR TITLE
Update for LLVM backend interface changes.

### PR DESCRIPTION
**Pull request by chathhorn**
Changes I needed to get the beacon chain stuff to build with the latest LLVM backend.

### CODE REVIEW

**Comment by dwightguth** [comment]
I was going to get around to this but it looks like you beat me to it.

**Comment by dwightguth** [comment]
looks like you need to modify the jenkinsfile to also clone the llvm backend recursively though. there should be a snippet for how to do that based on libff in the file already.

**Comment by chathhorn** [comment]
@dwightguth Jenkins doesn't seem to be using my Jenkinsfile? Is this maybe a permissions thing?

**Comment by dwightguth** [comment]
Yeah it's a permissions issue. I will try and get you the necessary permissions.

**Comment by dwightguth** [comment]
Try building it again now.

**Pull request merged**
