### PR TITLE
Update build process

### PR DESCRIPTION
**Pull request by sskeirik**
- use Dockerfile with builtin K
- add library dependencies as submodules (including recent libcrypto++ that we need, see #94)
- update Makefile to build submodules
- update Jenkinsfile build process to directly call Makefile

### CODE REVIEW

**Comment by ehildenb** [comment]
Why is K being included as a dependency here @sskeirik ? I think it should not be necessary.

KEVM bundles its own K, and so should other semantics, because the build system here may not be what is needed there.

Please also open a PR into KEVM showing how the build system there should be modified, and link this PR to that one.

You'll notice that KEVM, in particular, also bundles its own `libff`. So if you want to include `libff` here, then it should be removed from KEVM. Is it the case that Tezos also needs `libff`? Then it would make sense to put it here.

But the build system here _only_ exists to test that we know how to build the libraries, it was not designed to actually be used by the dependents directly (KEVM for example, has its own logic for building all the stuff here). So, if you want to make it modular in this way, please make sure it works with a PR into KEVM which shows that it is modular (by removing all the stuff about building plugin components from KEVM Makefile and adding calls to the Makefile here).

**Comment by sskeirik** [comment]
@ehildenb You probably already noticed this --- I explicitly don't include K as a submodule, because that would be redundant with other projects; I just include a pointer to a version of K that we can use to select a K dockerfile. The advantage here is twofold:

1. Jenkins doesn't have to clone the LLVM backend submodule and do any build logic --- almost all of the time, the K framework should be in the Docker build cache, so we can import it very cheaply.
2. Including a full K allows us to support a full integration test later in CI, if we want --- e.g. we can create a dummy semantics that just invokes hooks and checks that their results match what we expect.

As far as `libff` is concerned, we previously did implicitly have a `libff` submodule at the level of the Jenkinsfile. I just extracted the build logic into an explicit git submodule and into the Makefile. This has the following advantages:

1. It can be reused later --- I have a pull request for KEVM that I am working that replaces its build logic for the various libraries we need by an invocation to this Makefile.
2. The Jenkinsfile becomes simpler --- it just calls the Makefile.
3. It also encourages different semantics that use the plugin to upstream their changes --- it is easier to do a test build of changes when the build logic doesn't require an invocation of the Jenkins build server.

**Comment by sskeirik** [comment]
@ehildenb I noticed that KEVM bundles its own `libsecp256k1`, which is pinned to the same version that the Ubuntu package is built from. Since `libsecp256k1` is fairly widely packaged --- at least, Debian/Ubuntu/Arch all have official packages and OSX/Brew has an unofficial one --- how do you feel about assuming that the user pre-installs `libsecp256k1` before building?

On the other hand, if for some reason we want to use a more recent version of the library, I would be happy to add a submodule to this repo and reuse the build logic in KEVM.

Thoughts?

**Comment by ehildenb** [comment]
@sskeirik you're correct about libsecp256k1, but please don't add a submodule right now. We haven't had any users complain about that part of the build process, so there is no need to make it simpler.

Better to remove `libsecp256k1` entirely from the `Makefile` (since we just depend on the system installed version there), but leave the warning in the README.

Also, as long as the build system here becomes modular enough to be re-used, and libff gets removed as a submodule from KEVM, then these changes look good. I agree with all your reasoning, just want to make sure that we're not going overkill here.

**Comment by ehildenb** [comment]
Let's get #97 merged first so that you can remove those changes from this PR.

Best when you realize you're making changes to two different systems in the same repo to make separate PRs for them, everything tends to get merged faster that way.

**Pull request closed without merging**
